[package]
name = "sarzak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
uuid = { version = "1.2.2", features = ["v5", "serde"] }
nut = { path = "../nut" }
snafu = "0.7.4"
