[domains]
sarzak = { path = "models/sarzak.json", module = "sarzak", sarzak = { new = true, meta = true, doc_tests = true, extrude = false, ignore_ignore = false } }
drawing = { path = "models/drawing.json", module = "drawing", sarzak = { new = true, meta = true, doc_tests = true, extrude = false, ignore_ignore = false } }

[domains.woog]
path = "models/woog.json"
module = "woog"

[domains.woog.sarzak]
new = true
meta = true
doc_tests = true
extrude = false
ignore_ignore = false
