[modules."v2/lu_dog"]
model = "models/lu_dog.json"

[modules."v2/lu_dog".compiler]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
imported_domains = ["v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]

[modules."v2/lu_dog".compiler.target]
optimization_level = "None"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = false
uber_store = "Single"
target = "domain"

[modules."v2/lu_dog_vec"]
model = "models/lu_dog.json"

[modules."v2/lu_dog_vec".compiler]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
imported_domains = ["v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]

[modules."v2/lu_dog_vec".compiler.target]
optimization_level = "Vec"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = false
uber_store = "Single"
target = "domain"

[modules."v2/lu_dog_async"]
model = "models/lu_dog.json"

[modules."v2/lu_dog_async".compiler]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
imported_domains = ["v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]

[modules."v2/lu_dog_async".compiler.target]
optimization_level = "None"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = false
uber_store = "AsyncRwLock"
target = "domain"

[modules."v2/lu_dog_vanilla"]
model = "models/lu_dog.json"

[modules."v2/lu_dog_vanilla".compiler]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
imported_domains = ["v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]

[modules."v2/lu_dog_vanilla".compiler.target]
optimization_level = "None"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = false
uber_store = "Disabled"
target = "domain"

[modules."v2/lu_dog_rwlock"]
model = "models/lu_dog.json"

[modules."v2/lu_dog_rwlock".compiler]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
imported_domains = ["v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]

[modules."v2/lu_dog_rwlock".compiler.target]
optimization_level = "None"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = false
uber_store = "StdRwLock"
target = "domain"

[modules."v2/lu_dog_pl_mutex"]
model = "models/lu_dog.json"

[modules."v2/lu_dog_pl_mutex".compiler]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
imported_domains = ["v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]

[modules."v2/lu_dog_pl_mutex".compiler.target]
optimization_level = "None"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = false
uber_store = "ParkingLotMutex"
target = "domain"

[modules."v2/drawing"]
model = "models/drawing.json"

[modules."v2/drawing".compiler]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
imported_domains = ["v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]

[modules."v2/drawing".compiler.target]
optimization_level = "None"
from_module = "v1::drawing"
from_path = "models/drawing.json"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = true
uber_store = "Disabled"
target = "domain"

[modules."v2/merlin"]
model = "models/merlin.json"

[modules."v2/merlin".compiler]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
imported_domains = ["v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]

[modules."v2/merlin".compiler.target]
optimization_level = "None"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = false
uber_store = "Disabled"
target = "domain"

[modules."v2/sarzak"]
model = "models/sarzak.json"

[modules."v2/sarzak".compiler]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
use_paths = ["serde::{Deserialize, Serialize}"]

[modules."v2/sarzak".compiler.target]
optimization_level = "None"
from_module = "v1::sarzak"
from_path = "models/sarzak.json"
is_meta_model = true
is_sarzak = true
persist = true
persist_timestamps = true
uber_store = "Disabled"
target = "domain"

[modules."v2/woog"]
model = "models/woog.json"

[modules."v2/woog".compiler]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
imported_domains = ["v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]

[modules."v2/woog".compiler.target]
optimization_level = "None"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = true
uber_store = "Disabled"
target = "domain"
