[modules."v2/sarzak"]
model = "models/sarzak.json"

[modules."v2/sarzak".compiler]
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
use_paths = ["serde::{Deserialize, Serialize}"]
always_process = true

[modules."v2/sarzak".compiler.target]
target = "domain"
persist = true
persist_timestamps = true
from_module = "v1::sarzak"
from_path = "models/sarzak.json"

[modules."v2/drawing"]
model = "models/drawing.json"

[modules."v2/drawing".compiler]
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
imported_domains = ["v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]
always_process = true

[modules."v2/drawing".compiler.target]
target = "domain"
persist = true
persist_timestamps = true
from_module = "v1::drawing"
from_path = "models/drawing.json"

[modules."v2/woog"]
model = "models/woog.json"

[modules."v2/woog".compiler]
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
use_paths = ["serde::{Deserialize, Serialize}"]
imported_domains = ["v2/sarzak"]
always_process = true

[modules."v2/woog".compiler.target]
target = "domain"
persist = true
persist_timestamps = true
