[modules.sarzak_v2]
domain = "models/sarzak_✨.json"

[modules.sarzak_v2.compiler]
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
use_paths = ["serde::{Deserialize, Serialize}"]
imported_objects = false
target = "Domain"

[modules.drawing_v2]
domain = "models/drawing.json"

[modules.drawing_v2.compiler]
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
use_paths = ["serde::{Deserialize, Serialize}"]
imported_objects = false
target = "Domain"

# [modules.woog]
# domain = "models/woog.json"

# [modules.woog.compiler]
# compiler = "grace"
# derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
# use_paths = ["serde::{Deserialize, Serialize}"]
# imported_objects = false
# target = "Domain"
