#
# Lu Dog
#
[modules."v2/lu_dog"]
model = "models/lu_dog.json"

[[modules."v2/lu_dog".compiler]]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
imported_domains = ["crate/v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]
tracy = false

[modules."v2/lu_dog".compiler.target]
optimization_level = "None"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = false
uber_store = "Single"
target = "domain"

#
# Lu Dog Vec
#
[modules."v2/lu_dog_vec"]
model = "models/lu_dog.json"

[[modules."v2/lu_dog_vec".compiler]]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "Serialize"]
imported_domains = ["crate/v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]
tracy = false

[modules."v2/lu_dog_vec".compiler.target]
optimization_level = "Vec"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = false
uber_store = "Single"
target = "domain"

#
# Lu Dog Vec Tracy
#
[modules."v2/lu_dog_vec_tracy"]
model = "models/lu_dog.json"

[[modules."v2/lu_dog_vec_tracy".compiler]]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "Serialize"]
imported_domains = ["crate/v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]
tracy = true

[modules."v2/lu_dog_vec_tracy".compiler.target]
optimization_level = "Vec"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = false
uber_store = "Single"
target = "domain"

#
# Lu Dog RwLock Vec
#
[modules."v2/lu_dog_rwlock_vec"]
model = "models/lu_dog.json"

[[modules."v2/lu_dog_rwlock_vec".compiler]]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "Serialize"]
imported_domains = ["crate/v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]
tracy = false

[modules."v2/lu_dog_rwlock_vec".compiler.target]
optimization_level = "Vec"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = false
uber_store = "StdRwLock"
target = "domain"

#
# Lu Dog Parking Lot Vec
#
[modules."v2/lu_dog_pl_vec"]
model = "models/lu_dog.json"

[[modules."v2/lu_dog_pl_vec".compiler]]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "Serialize"]
imported_domains = ["crate/v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]
tracy = false

[modules."v2/lu_dog_pl_vec".compiler.target]
optimization_level = "Vec"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = false
uber_store = "ParkingLotRwLock"
target = "domain"

#
# Lu Dog No Deadlocks RwLock Vec
#
[modules."v2/lu_dog_ndrwlock_vec"]
model = "models/lu_dog.json"

[[modules."v2/lu_dog_ndrwlock_vec".compiler]]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "Serialize"]
imported_domains = ["crate/v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]
tracy = false

[modules."v2/lu_dog_ndrwlock_vec".compiler.target]
optimization_level = "Vec"
is_meta_model = true
is_sarzak = false
persist = false
persist_timestamps = false
uber_store = "NDRwLock"
target = "domain"

#
# Lu Dog Async
#
[modules."v2/lu_dog_async"]
model = "models/lu_dog.json"

[[modules."v2/lu_dog_async".compiler]]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "Serialize"]
imported_domains = ["crate/v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]
tracy = false

[modules."v2/lu_dog_async".compiler.target]
optimization_level = "Vec"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = false
uber_store = "AsyncRwLock"
target = "domain"

#
# Lu Dog WTF?
#
[modules."v2/lu_dog_vanilla"]
model = "models/lu_dog.json"

[[modules."v2/lu_dog_vanilla".compiler]]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
imported_domains = ["crate/v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]
tracy = false

[modules."v2/lu_dog_vanilla".compiler.target]
optimization_level = "None"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = false
uber_store = "Disabled"
target = "domain"

#
# Lu Dog RwLock
#
[modules."v2/lu_dog_rwlock"]
model = "models/lu_dog.json"

[[modules."v2/lu_dog_rwlock".compiler]]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
imported_domains = ["crate/v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]
tracy = false

[modules."v2/lu_dog_rwlock".compiler.target]
optimization_level = "None"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = false
uber_store = "StdRwLock"
target = "domain"

#
# Drawing
#
[modules."v2/drawing"]
model = "models/drawing.json"

[[modules."v2/drawing".compiler]]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
imported_domains = ["crate/v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]
tracy = false

[modules."v2/drawing".compiler.target]
optimization_level = "None"
from_module = "v1::drawing"
from_path = "models/drawing.json"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = false
uber_store = "StdRwLock"
target = "domain"

#
# Merlin
#
[modules."v2/merlin"]
model = "models/merlin.json"

[[modules."v2/merlin".compiler]]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
imported_domains = ["crate/v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]
tracy = false

[modules."v2/merlin".compiler.target]
optimization_level = "None"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = false
uber_store = "StdRwLock"
target = "domain"

#
# Sarzak
#
[modules."v2/sarzak"]
model = "models/sarzak.json"

[[modules."v2/sarzak".compiler]]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
use_paths = ["serde::{Deserialize, Serialize}"]
tracy = false

[modules."v2/sarzak".compiler.target]
optimization_level = "None"
from_module = "v1::sarzak"
from_path = "models/sarzak.json"
is_meta_model = true
is_sarzak = true
persist = true
persist_timestamps = true
uber_store = "StdRwLock"
target = "domain"

#
# Sarzak Single
#
[modules."v2/sarzak_single"]
model = "models/sarzak.json"

[[modules."v2/sarzak_single".compiler]]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
use_paths = ["serde::{Deserialize, Serialize}"]
tracy = false

[modules."v2/sarzak_single".compiler.target]
optimization_level = "None"
from_module = "v1::sarzak"
from_path = "models/sarzak.json"
is_meta_model = true
is_sarzak = true
persist = true
persist_timestamps = false
uber_store = "Disabled"
target = "domain"

#
# Woog
#
[modules."v2/woog"]
model = "models/woog.json"

[[modules."v2/woog".compiler]]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
imported_domains = ["crate/v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]
tracy = false

[modules."v2/woog".compiler.target]
optimization_level = "None"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = false
uber_store = "StdRwLock"
target = "domain"

#
# Woog Single
#
[modules."v2/woog_single"]
model = "models/woog.json"

[[modules."v2/woog_single".compiler]]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
imported_domains = ["crate/v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]
tracy = false

[modules."v2/woog_single".compiler.target]
optimization_level = "None"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = false
uber_store = "Disabled"
target = "domain"
