[modules."v2/sarzak"]
domain = "models/sarzak_✨.json"

[modules."v2/sarzak".compiler]
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
use_paths = ["serde::{Deserialize, Serialize}"]
target = "Domain"

[modules."v2/drawing"]
domain = "models/drawing_✨.json"

[modules."v2/drawing".compiler]
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
imported_domains = ["v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]
target = "Domain"

[modules."v2/woog"]
domain = "models/woog_✨.json"

[modules."v2/woog".compiler]
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
use_paths = ["serde::{Deserialize, Serialize}"]
imported_domains = ["v2/sarzak"]
target = "Domain"
