[modules.sarzak]
domain = "models/sarzak_✨.json"

[modules.sarzak.compiler]
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
use_paths = ["serde::{Deserializa, Serialize}"]
imported_objects = false
target = "Domain"

[modules.drawing]
domain = "models/drawing.json"

[modules.drawing.compiler]
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
use_paths = ["serde::{Deserializa, Serialize}"]
imported_objects = false
target = "Domain"

[modules.woog]
domain = "models/woog.json"

[modules.woog.compiler]
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
use_paths = ["serde::{Deserializa, Serialize}"]
imported_objects = false
target = "Domain"
