[domains]
sarzak = { path = "models/sarzak.json", module = "sarzak_v1", sarzak = { new = true, meta = true, doc_tests = true, extrude = false, ignore_ignore = true } }
drawing = { path = "models/drawing.json", module = "drawing_v1", sarzak = { new = true, meta = true, doc_tests = true, extrude = false, ignore_ignore = true } }
