[domains]
sarzak = { path = "models/sarzak.json", module = "sarzak", sarzak = { meta = true, doc_tests = true, extrude = true, ignore_ignore = false } }
drawing = { path = "models/drawing.json", module = "drawing", sarzak = { meta = true, doc_tests = true, extrude = true, ignore_ignore = false } }
