//! Drawing Domain
//!
//! This file was generated by: `sarzak new "drawing"`.
use uuid::{uuid, Uuid};

pub mod from;
pub mod store;
pub mod types;

pub use store::ObjectStore;
pub use types::*;

// drawing
pub const UUID_NS: Uuid = uuid!("0d035b17-076b-5848-b20f-ee05ce7738a9");
