//! Lu Dog Domain
//!
//! This file was generated by: `sarzak new "lu_dog"`.
use uuid::{uuid, Uuid};

pub mod macros;
pub mod store;
pub mod types;

pub use store::ObjectStore;
pub use types::*;
pub use macros::*;

// lu_dog
pub const UUID_NS: Uuid = uuid!("718a3c7b-8124-5b12-bf4f-6ff6274db22c");

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test() {
    }
}
