//! Woog Domain
//!
//! This file was generated by: `sarzak new "woog"`.
use uuid::{uuid, Uuid};

#[macro_use]
pub mod macros;
pub mod store;
pub mod types;

pub use store::ObjectStore;
pub use types::*;

// woog
pub const UUID_NS: Uuid = uuid!("288d4258-fdbd-52dd-a38b-976fd132d096");

pub fn init_instances(store: &mut ObjectStore) {
    // Initialize with primitives.
    store.inter_visibility(Visibility::Public(PUBLIC));
    store.inter_visibility(Visibility::Private(PRIVATE));
    store.inter_visibility(Visibility::Crate(CRATE));

    store.inter_mutability(Mutability::Mutable(MUTABLE));
    store.inter_mutability(Mutability::Borrowed(BORROWED));
}
