//! Woog Domain
//!
//! This file was generated by: `sarzak new "woog"`.
use uuid::{uuid, Uuid};

pub mod macros;
pub mod store;
pub mod types;

pub use store::ObjectStore;
pub use types::*;
pub use macros::*;

// woog
pub const UUID_NS: Uuid = uuid!("288d4258-fdbd-52dd-a38b-976fd132d096");

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test() {
    }
}
